# Generated by Django 4.2.8 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_badge_userpoints_notification_announcement_userbadge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="enrollment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(enrollment_id__isnull=False),
                fields=("enrollment_id",),
                name="unique_enrollment_id_when_set",
            ),
        ),
    ]
