# Generated by Django 4.2.8 on 2026-02-03 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("mcq", "MCQ"),
                            ("mixed", "Mixed"),
                            ("coding", "Coding"),
                            ("descriptive", "Descriptive"),
                        ],
                        default="mixed",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("duration", models.IntegerField()),
                ("total_marks", models.DecimalField(decimal_places=2, max_digits=10)),
                ("passing_marks", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_published", models.BooleanField(default=False)),
                ("instructions", models.TextField(blank=True, null=True)),
                ("allowed_departments", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_exams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "exams",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("submit_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("auto_submitted", "Auto Submitted"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "obtained_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="exams.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "exam_attempts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mcq", "MCQ"),
                            ("multiple_mcq", "Multiple Choice MCQ"),
                            ("descriptive", "Descriptive"),
                            ("coding", "Coding"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.TextField()),
                ("points", models.DecimalField(decimal_places=2, max_digits=10)),
                ("options", models.JSONField(blank=True, default=list)),
                ("correct_answers", models.JSONField(blank=True, default=list)),
                (
                    "coding_language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("python", "Python"),
                            ("java", "Java"),
                            ("javascript", "JavaScript"),
                            ("cpp", "C++"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("test_cases", models.JSONField(blank=True, default=list)),
                ("sample_input", models.TextField(blank=True, null=True)),
                ("sample_output", models.TextField(blank=True, null=True)),
                ("sample_answer", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "db_table": "questions",
                "ordering": ["order"],
                "unique_together": {("exam", "order")},
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answer", models.JSONField()),
                ("code", models.TextField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("feedback", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exams.examattempt",
                    ),
                ),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluated_answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exams.question",
                    ),
                ),
            ],
            options={
                "db_table": "answers",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_marks", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "obtained_marks",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "status",
                    models.CharField(
                        choices=[("pass", "Pass"), ("fail", "Fail")], max_length=20
                    ),
                ),
                ("submitted_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="exams.examattempt",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="exams.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "results",
                "ordering": ["-created_at"],
                "unique_together": {("exam", "student")},
            },
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["exam", "student"], name="exam_attemp_exam_id_584314_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(fields=["status"], name="exam_attemp_status_db025a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="examattempt",
            unique_together={("exam", "student")},
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["start_time"], name="exams_start_t_bab18d_idx"),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["end_time"], name="exams_end_tim_7705f0_idx"),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["is_published"], name="exams_is_publ_8bb3b8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("attempt", "question")},
        ),
    ]
