# Generated by Django 6.0.2 on 2026-02-12 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0004_result_grading_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["attempt", "question"], name="answers_attempt_2fb0d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["question", "attempt"], name="answers_questio_f1f453_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(fields=["attempt"], name="answers_attempt_022a6b_idx"),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(fields=["question"], name="answers_questio_3d2018_idx"),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(fields=["score"], name="answers_score_ca5cab_idx"),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["created_at"], name="answers_created_a5b46e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["created_by"], name="exams_created_7a6aa4_idx"),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["start_time", "end_time"], name="exams_start_t_d9bb07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["is_published", "start_time"], name="exams_is_publ_6594a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["student", "exam"], name="exam_attemp_student_1c018c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["start_time"], name="exam_attemp_start_t_2e8167_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["submit_time"], name="exam_attemp_submit__6e8068_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["status", "exam"], name="exam_attemp_status_88e5fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["student", "status"], name="exam_attemp_student_2b62bc_idx"
            ),
        ),
    ]
