# Generated by Django 6.0.2 on 2026-02-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_answer_answers_attempt_2fb0d3_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="answer",
            name="answers_attempt_2fb0d3_idx",
        ),
        migrations.RemoveIndex(
            model_name="answer",
            name="answers_questio_f1f453_idx",
        ),
        migrations.RemoveIndex(
            model_name="answer",
            name="answers_attempt_022a6b_idx",
        ),
        migrations.RemoveIndex(
            model_name="answer",
            name="answers_questio_3d2018_idx",
        ),
        migrations.RemoveIndex(
            model_name="answer",
            name="answers_score_ca5cab_idx",
        ),
        migrations.RemoveIndex(
            model_name="answer",
            name="answers_created_a5b46e_idx",
        ),
    ]
