# Generated by Django 4.2.8 on 2026-02-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0006_remove_answer_answers_attempt_2fb0d3_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("mcq", "MCQ"),
                    ("multiple_mcq", "Multiple Choice MCQ"),
                    ("true_false", "True/False"),
                    ("short_answer", "Short Answer"),
                    ("long_answer", "Long Answer"),
                    ("descriptive", "Descriptive"),
                    ("coding", "Coding"),
                ],
                max_length=20,
            ),
        ),
    ]
